[default.databases.mysql_test]
url = "mysql://root:YDmfA59Qj4xI0yDUXhxf@containers-us-west-52.railway.app:7286/railway"
min_connections = 64
max_connections = 1024
connect_timeout = 5
idle_timeout = 120

